[package]
name = "stack-reorder"
description = "A Rust contract that has stack reordered at lower address"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.15.0"

[build-dependencies]
cc = "1.0"
