name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install llvm 16
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 16 && rm llvm.sh
    - name: Install riscv64 target
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Build and test
      run: make

  macos-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install llvm 16
      run: brew install llvm@16
    - name: Install riscv64 target
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Build and test
      run: PATH="/usr/local/opt/llvm@16/bin:$PATH" make LLVM_PREFIX=""
